### ISSUE TITLE
mv: cannot remove '/etc/bind': Directory not empty

### ISSUE THREAD

**Issue by littlewitchanita** [sameersbn/docker-bind#24] opened 2017-02-22 13:03 UTC
pulled latest version using latest version of docker for centos7

run by:
docker run --name bind -d \
  --publish 53:53/tcp --publish 53:53/udp --publish 10000:10000/tcp \
  --volume /srv/docker/bind:/data \
  sameersbn/bind

got this error when starting the container:
mv: cannot remove '/etc/bind': Directory not empty

**Comment by lorenzvth7** [comment] 2017-03-06 07:50
+1

**Comment by lorenzvth7** [comment] 2017-03-06 08:49
https://github.com/docker/docker/issues/27214

**Comment by sameersbn** [comment] 2017-06-26 16:09
@littlewitchanita @lvthillo sorry for the lateness of my response. I believe the issue is because you're using  the overlayfs storage driver for the docker daemon along with XFS. 

OverlayFS remains a Technology Preview in Red Hat Enterprise Linux 7.2 under most circumstances. Please refer to https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html for additional details and recommended actions to take for getting XFS and OverlayFS to play nicely on these distros.

Closing the issue, please let us know if this helped.

**Closed by sameersbn** 2017-06-26 16:09 UTC
